# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

# strategy:
#   matrix:
#     node_12_x:
#       node_version: 12.x
#     node_13_x:
#       node_version: 13.x


steps:
- task: NodeTool@0 
  inputs:
    versionSpec: 13.x


- task: Npm@1
  inputs:
    command: 'install'
    verbose: true

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'build'

# - script: mocha test --reporter mocha-junit-reporter
#   displayName: 'Run Mocha test'

# - task: PublishTestResults@2
#   inputs:
#     testResultsFiles: '**/TEST-RESULTS.xml'
#     testRunTitle: 'Test results for JavaScript using gulp'

# - task: PublishCodeCoverageResults@1
#   inputs: 
#     codeCoverageTool: Cobertura
#     summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
#     reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'


# - script: npm run build
#   displayName: 'npm build'

    
# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(System.DefaultWorkingDirectory)'